---
k3s:
  # Ref: https://github.com/rancher/k3s/releases
  version: "1.0.1"

  # Shared token for node joining. Set to any random string
  token: "ahkie0kohcub7wun6eeg7Eengee1ael8"

  # Ref: https://rancher.com/docs/k3s/latest/en/installation/datastore/#datastore-endpoint-format-and-functionality
  # Default: etcd.local
  datastoreEndpoint: ""
  
  # Used for cluster name and agent joining cluster using name
  # Set to name that resolves to all master nodes
  # Default: k3s.local
  clusterName: ""

master:
  count: 3  # How many master nodes
  specs:
    box: "ubuntu/bionic64"
    eth1: "172.20.22.10"  # First master IP
    cpu: 1
    mem: 1024
  k3sParams: "--no-deploy traefik --no-deploy servicelb --no-deploy metrics-server --node-taint k3s-controlplane=true:NoExecute"

worker:
  count: 3  # How many master nodes
  specs:
    box: "ubuntu/bionic64"
    eth1: "172.20.22.20"  # First master IP
    cpu: 1
    mem: 1024
  k3sParams: ""

# Array of additinal entries to add to /etc/hosts file
# Format: IP DNS
hosts: []
# - 10.10.10.10 example.com

